import { 
  Button, 
  Uploader, 
  Form, 
  PasswordInput, 
  Loading, 
  Field,
  Search,
  NoticeBar,
  ImagePreview,
  Divider,
  Lazyload,
  List,
  Sticky,
  Tag,
  Grid,
  IndexBar,
  Tabbar,
  PullRefresh,
  Overlay,
  Switch,
  Stepper,
  Rate,
  Radio,
  Picker,
  DatetimePicker,
  Checkbox,
  CheckboxGroup,
  Toast,
  Popup,
  Col, 
  Row,
  Image,
  Icon,
  GridItem,
  Empty,
  TabbarItem,
  SwipeItem,
  Swipe,
  Cell,
  CellGroup,
  RadioGroup,
  Dialog,
  DropdownMenu,
  DropdownItem,
  SwipeCell
} from 'vant'

export default {
  install(Vue) {
    Vue.use(Button)
    Vue.use(Uploader)
    Vue.use(Form)
    Vue.use(PasswordInput)
    Vue.use(Loading)
    Vue.use(Field)
    Vue.use(Search)
    Vue.use(NoticeBar)
    Vue.use(Icon)
    Vue.use(Image)
    Vue.use(Row)
    Vue.use(Col)
    Vue.use(Popup)
    Vue.use(Toast)
    Vue.use(Checkbox)
    Vue.use(DatetimePicker)
    Vue.use(Picker)
    Vue.use(Radio)
    Vue.use(Rate)
    Vue.use(Stepper)
    Vue.use(Switch)
    Vue.use(ImagePreview)
    Vue.use(Divider)
    Vue.use(Lazyload)
    Vue.use(List)
    Vue.use(Sticky)
    Vue.use(Tag)
    Vue.use(Grid)
    Vue.use(IndexBar)
    Vue.use(Tabbar)
    Vue.use(PullRefresh)
    Vue.use(Overlay)
    Vue.use(GridItem)
    Vue.use(Empty)
    Vue.use(TabbarItem)
    Vue.use(SwipeItem)
    Vue.use(Swipe)
    Vue.use(Cell)
    Vue.use(CellGroup)
    Vue.use(RadioGroup)
    Vue.use(Dialog)
    Vue.use(DropdownItem)
    Vue.use(DropdownMenu)
    Vue.use(CheckboxGroup)
    Vue.use(SwipeCell)
  }
}