name: build
on: 
  push: 
    branches: 
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy 
        uses: actions/aliyun-deploy-for-self@v1
        with:
          remote_path: ${{secrets.REMOTE_PATH}}
          remote_path_prev: ${{secrets.TEMP_REMOTE_PATH}}
          need_merge: 'true'
          merge_file_dir: './static,./.nuxt,./package.json,./nuxt.config.js,./pm2.config.js'
          remote_action_install: yarn -production
          remote_action_start: yarn start:production
           
